openapi: 3.0.0
info:
  title: API de Carrito y Órdenes
  description: Microservicio NestJS para gestionar carritos de compra y órdenes en PulgaShop.
  version: 1.0.0
  contact:
    name: Equipo PulgaShop
servers:
  - url: /api/v1
    description: Prefijo global configurado en la aplicación NestJS
tags:
  - name: carrito
    description: Endpoints para crear, modificar y consultar carritos
  - name: ordenes
    description: Endpoints para checkout, historial y estadísticas de órdenes
paths:
  /carrito/crearCarrito:
    post:
      tags:
        - carrito
      summary: Crear un carrito para un comprador
      operationId: crearCarrito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrearCarritoRequest'
      responses:
        '201':
          description: Carrito creado o recuperado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarritoDetallado'
        '400':
          description: Datos inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /carrito/eliminarCarrito:
    delete:
      tags:
        - carrito
      summary: Eliminar un carrito
      description: Permite eliminar por completo un carrito. Si no se entrega carritoId, se elimina el último carrito del comprador.
      operationId: eliminarCarrito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EliminarCarritoRequest'
      responses:
        '200':
          description: Carrito eliminado (se devuelve el snapshot del carrito)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarritoDetallado'
        '404':
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /carrito/obtenerCarritos:
    get:
      tags:
        - carrito
      summary: Obtener todos los carritos
      operationId: obtenerCarritos
      responses:
        '200':
          description: Lista de carritos con sus items hidratados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CarritoDetallado'
  /carrito/obtenerCarro/{id}:
    get:
      tags:
        - carrito
      summary: Obtener un carrito por ID
      operationId: obtenerCarritoPorId
      parameters:
        - name: id
          in: path
          description: Identificador del carrito
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Carrito encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarritoDetallado'
        '404':
          description: Carrito inexistente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /carrito/agregarProductos:
    post:
      tags:
        - carrito
      summary: Agregar o incrementar un producto en el carrito
      operationId: agregarProducto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgregarProductoRequest'
      responses:
        '201':
          description: Carrito actualizado con el producto agregado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarritoDetallado'
        '400':
          description: Stock insuficiente o payload inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /carrito/eliminarProducto:
    delete:
      tags:
        - carrito
      summary: Eliminar o decrementar un producto del carrito
      operationId: eliminarProducto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EliminarProductoRequest'
      responses:
        '200':
          description: Carrito actualizado tras eliminar el producto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarritoDetallado'
        '400':
          description: Cantidad inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Carrito o producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /ordenes/checkout/{carritoId}:
    post:
      tags:
        - ordenes
      summary: Crear una orden a partir de un carrito
      operationId: checkout
      parameters:
        - name: carritoId
          in: path
          required: true
          description: Identificador del carrito que se desea cerrar
          schema:
            type: integer
            minimum: 1
      responses:
        '201':
          description: Orden creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orden'
        '500':
          description: Error al crear la orden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /ordenes/estado-pago/{carritoId}:
    get:
      tags:
        - ordenes
      summary: Consultar el estado de pago asociado a un carrito
      operationId: obtenerEstadoPago
      parameters:
        - name: carritoId
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Estado de pago actual o NO_EXISTE si el carrito no posee orden vinculada
          content:
            application/json:
              schema:
                type: string
                example: PENDIENTE
  /ordenes/historial/{compradorId}:
    get:
      tags:
        - ordenes
      summary: Obtener historial de órdenes por comprador
      operationId: obtenerHistorialOrdenes
      parameters:
        - name: compradorId
          in: path
          description: Identificador del comprador
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Historial ordenado descendentemente por fecha de creación
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Orden'
        '404':
          description: El comprador no posee órdenes registradas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /ordenes/estadisticas/producto/{productoId}:
    get:
      tags:
        - ordenes
      summary: Obtener estadísticas de órdenes asociadas a un producto
      operationId: obtenerEstadisticasProducto
      parameters:
        - name: productoId
          in: path
          description: Identificador del producto
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Estadísticas calculadas desde las órdenes y carritos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EstadisticasProducto'
components:
  schemas:
    ProductoDetalle:
      type: object
      description: Información de catálogo del producto cargada desde productos.txt
      properties:
        id:
          type: integer
          example: 101
        name:
          type: string
          example: Collar luminiscente
        description:
          type: string
          example: Collar reflectante para mascotas nocturnas
        price:
          type: number
          format: integer
          example: 19990
        quantity:
          type: integer
          description: Stock disponible en el catálogo
          example: 50
        category:
          type: string
          example: accesorios
        imageUrl:
          type: string
          format: uri
          example: https://cdn.pulgashop.com/products/101.png
    CarritoItem:
      type: object
      description: Línea dentro de un carrito con datos de catálogo incluidos
      properties:
        productoId:
          type: integer
          example: 101
        cantidad:
          type: integer
          example: 3
        precio:
          type: number
          format: integer
          description: Precio unitario almacenado en el carrito
          example: 19990
        name:
          type: string
          example: Collar luminiscente
        description:
          type: string
        category:
          type: string
          example: accesorios
        imageUrl:
          type: string
          format: uri
        quantity:
          type: integer
          description: Stock total reportado en el catálogo al momento de la lectura
          example: 50
      required:
        - productoId
        - cantidad
        - precio
    CarritoDetallado:
      type: object
      description: Representación persistida del carrito con items hidratados
      properties:
        id:
          type: integer
          example: 12
        compradorId:
          type: string
          example: user_abc123
        total:
          type: number
          format: integer
          example: 59997
        items:
          type: array
          items:
            $ref: '#/components/schemas/CarritoItem'
        createdAt:
          type: string
          format: date-time
          example: 2025-11-20T21:45:00Z
        updatedAt:
          type: string
          format: date-time
          example: 2025-11-20T21:47:35Z
    CrearCarritoRequest:
      type: object
      properties:
        compradorId:
          type: string
          description: Identificador único del comprador
          example: user_abc123
      required:
        - compradorId
    EliminarCarritoRequest:
      type: object
      properties:
        compradorId:
          type: string
          description: Comprador dueño del carrito a eliminar
          example: user_abc123
        carritoId:
          type: integer
          description: Identificador del carrito (opcional). Si se omite, se eliminará el más reciente.
      required:
        - compradorId
    AgregarProductoRequest:
      type: object
      properties:
        compradorId:
          type: string
          example: user_abc123
        productoId:
          type: integer
          example: 101
        cantidad:
          type: integer
          minimum: 1
          example: 2
      required:
        - compradorId
        - productoId
        - cantidad
    EliminarProductoRequest:
      type: object
      properties:
        compradorId:
          type: string
          example: user_abc123
        productoId:
          type: integer
          example: 101
        cantidad:
          type: integer
          minimum: 1
          description: Cantidad a eliminar; si es mayor o igual a la cantidad en el carrito, se elimina el item completo.
          example: 1
      required:
        - compradorId
        - productoId
        - cantidad
    Orden:
      type: object
      description: Orden de compra generada a partir de un carrito
      properties:
        id:
          type: integer
          example: 45
        carritoId:
          type: integer
          example: 12
        compradorId:
          type: string
          example: user_abc123
        estadoPago:
          type: string
          enum:
            - PENDIENTE
            - PAGADO
            - CANCELADO
          example: PENDIENTE
        total:
          type: number
          format: integer
          example: 59997
        fechaCreacion:
          type: string
          format: date-time
          example: 2025-11-20T21:48:12Z
    EstadisticasProducto:
      type: object
      description: Métricas agregadas sobre órdenes y carritos vinculados a un producto
      properties:
        vecesComprado:
          type: integer
          example: 10
        vecesCancelado:
          type: integer
          example: 2
        carritosCompletados:
          type: integer
          example: 8
        carritosAbandonados:
          type: integer
          example: 4
    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 404
        message:
          type: string
          example: Carrito para el comprador user_abc123 no encontrado.
        error:
          type: string
          example: Not Found
